### ISSUE TITLE
`BpCausal` with no controls

### ISSUE THREAD

**Issue by dklinenberg2020** [liulch/bpCausal#2]
Hello,

I'm very interested in `BpCausal`. I'd like to compare my proposed Bayesian approach to synthetic control to `BpCausal`. However, my approach does not use covariates. I'm struggling in running `BpCausal` without covariates. I was hoping to do so, similarly to how one can run `Y~D` with `gsynth` when no covariates are included. 

Is there a workaround for `BpCausal`? Thanks!

**Comment by liulch** [comment]
Hi @dklinenberg2020 , yes! you can check the example in the markdown file: https://github.com/liulch/bpCausal. Just specify "Yname" and "Dname", and leave "Xname", "Zname" and "Aname" as NULL. We don't have a formula specification in bpCausal now but maybe we'll add an option.

**Comment by dklinenberg2020** [comment]
Oh very cool! I was trying `NA`. Thank you.

May I ask a quick question of clarification for your model: Unlike the work by Abadie, your approach doesn't explicitly estimate the counterfactual as a linear combination of untreated units. Rather, it uses the untreated units to estimate the factor loadings and uses those factor loadings to construct the counterfactual. When covariates are included, you allow the relationship to be static or time-varying. 

Is this the correct interpretation of your approach?

**Comment by liulch** [comment]
> Oh very cool! I was trying `NA`. Thank you.
> 
> May I ask a quick question of clarification for your model: Unlike the work by Abadie, your approach doesn't explicitly estimate the counterfactual as a linear combination of untreated units. Rather, it uses the untreated units to estimate the factor loadings and uses those factor loadings to construct the counterfactual. When covariates are included, you allow the relationship to be static or time-varying.
> 
> Is this the correct interpretation of your approach?

Yes! That's definitely right!

**Comment by dklinenberg2020** [comment]
Thank you!
