### ISSUE TITLE
bpCausal install issue

### ISSUE THREAD

**Issue by rachelnethery** [liulch/bpCausal#3]
Hi, thanks so much to the team for your very cool work and your dedication to providing open source software! I am able to install the group's other software packages (fect, gsynth, panelView), but when I try to install bpCausal I get the following error message:
<img width="770" alt="Screen Shot 2022-01-18 at 5 08 03 PM" src="https://user-images.githubusercontent.com/29979260/150026550-cd1b85e4-c7e5-41c4-bf7b-6b950e95a615.png">

Has this issue been reported before? I am thinking that maybe the most recent github commit may have gone to a branch other than master, and maybe that's what's causing the problem? Please let me know if you have any thoughts about how to resolve it.

Thanks!
Rachel Nethery

**Comment by liulch** [comment]
Hi Rachel,

It seems that I can install it from my laptop. So it's weird. could you please try downloading the package to your laptop and then install it?

<img width="663" alt="Screen Shot 2022-01-18 at 6 15 02 PM" src="https://user-images.githubusercontent.com/30182608/150034070-0a35382c-1bd1-49b0-8ca7-a68a9f789914.png">

**Comment by rachelnethery** [comment]
Thanks for the suggestion! Downloading the package and installing from source worked for me. I appreciate your help!

-Rachel
